### ISSUE TITLE
 IExceptionHandler implementation - how to catch unhandled exceptions in Android apps ?

### ISSUE THREAD

**Issue by abrasat** [CodonFramework/Codon#2]
How would a IExceptionHandler implementation for the Codon framework look like, in view to catch the Android unhandled exceptions AppDomain.CurrentDomain.UnhandledException, TaskScheduler.UnobservedTaskException, AndroidEnvironment.UnhandledExceptionRaiser ? Any sample available ?

**Comment by DVaughan** [comment]
Those events don't allow recovery from an unhandled exception in Android. I don't know of a global way to prevent an unhandled exception from causing the OS to exit your app in Android. Setting the RaiseThrowableEventArgs.Handled property to true has no effect. Nor does UnobservedTaskExceptionEventArgs.SetObserved.

The purpose of the IExceptionHandler in Codon is to allow handling of an exception before it reaches the top of the call stack. Please take a look at the [LoggingExceptionHandler](https://github.com/CodonFramework/Codon/blob/d0f7cd99ed4ae01a304d260fbc831d9b45099857/Source/Framework/Codon/ComponentModel/ExceptionHandling/LoggingExceptionHandler.cs)
It's used in Codon when executing user code (such as executing an ActionCommand), and is a way to prevent your code being littered with try/catch statements. It's a good idea to implement your own IExceptionHandler and register it with the IoC container, because LoggingExceptionHandler rethrows exceptions.
